spring.application.name=ecommerce-backend
#mysql icin ---
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
#spring.datasource.username=root
#spring.datasource.password=12345
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#-----------------------------

# Render'in bize verecegi ortam degiskenlerini (Environment Variables) buraya bagliyoruz
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.address=0.0.0.0
server.port=${PORT:8080}
#------------------------------
# PostgreSQL Surucu ve Lehce (Dialect) Ayarlari
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#--------------------------------------------------------------

# Hibernate'in tablolari degistirmesini KESINLIKLE engelle
spring.jpa.hibernate.ddl-auto=update
# Canlida SQL sorgularinin loglarda kabak gibi gorunmesini engelle (Guvenlik icin gizlenmeli)
spring.jpa.show-sql=false
#-------cloudinary-------
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_API_KEY}
cloudinary.api_secret=${CLOUD_API_SECRET}
#------------------------
#-------------------
#server.error.include-message=always
#server.address=0.0.0.0
#--------------------------------

#
# 256-bit veya daha uzun gizli anahtariniz
jwt.secret=404E635266556A586E327235753878214125442A472D4B6150645367566B5970
# Access Token suresi (15 Dakika = 900000 milisaniye)
jwt.access-token.expiration=900000
# Refresh Token suresi (7 Gun = 604800000 milisaniye)
jwt.refresh-token.expiration=604800000